### ISSUE TITLE
ssh-key-to-pem depricated -possible reason for throwing an error?

### ISSUE THREAD

**Issue by jholowicki** [greglobinski/gatsby-starter-personal-blog#41]
Hi, I'm trying to get your site to hot load, but when I hit enter on 'gatsby develop' I get an error like this: 
```
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.6.1/libvips-8.6.1-linux-x64.tar.gz

> svgr@2.0.0 postinstall /home/joie/Documents/personalsite/node_modules/svgr
> node message.js; sleep 10; exit 1;

/home/joie/Documents/personalsite/node_modules/ssh-key-to-pem/index.js:210
    throw new Error('Only RSA and DSA public keys are allowed');
    ^

Error: Only RSA and DSA public keys are allowed
    at sshKeyToPEM (/home/joie/Documents/personalsite/node_modules/ssh-key-to-pem/index.js:210:11)
    at toPEM (/home/joie/Documents/personalsite/node_modules/ghsign/index.js:28:52)
    at Array.map (<anonymous>)
    at /home/joie/Documents/personalsite/node_modules/ghsign/index.js:105:32
    at identitiesAnswer (/home/joie/Documents/personalsite/node_modules/ssh-agent/lib/ssh_agent_client.js:179:12)
    at Socket.<anonymous> (/home/joie/Documents/personalsite/node_modules/ssh-agent/lib/ssh_agent_client.js:280:12)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
```

as for https://github.com/dominictarr/ssh-key-to-pem -user says to use sshpk (https://www.npmjs.com/package/sshpk) instead

I saw another person was having issues with the SVGr portion as well... any idea?

**Comment by greglobinski** [comment]
@jholowicki If you have errors like this with `gatsby develop` it means that the `gatsby new` command did not installed correctly the dependencies. Show me you command line output after `gatsby new ...`

**Comment by jholowicki** [comment]
@greglobinski I just deleted it and re-downloaded it. The error after I commanded `gatsby new` is this:
![errorshot](https://user-images.githubusercontent.com/19287595/41495192-67b09ab0-70e7-11e8-8692-d07224a5adaf.png)

**Comment by greglobinski** [comment]
In new v.1.1.1 I removed svgr from the starter.
