### ISSUE TITLE
Error after selecting package manager

### ISSUE THREAD

**Issue by emanuallan** [greglobinski/gatsby-starter-personal-blog#95]
```
fatal error: too many errors emitted, stopping now [-ferror-limit=]
10 warnings and 20 errors generated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/12.1.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/Cellar/node/12.1.0/bin/node" "/usr/local/Cellar/node/12.1.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/aserna/Desktop/allanserna.blog/node_modules/gatsby-plugin-manifest/node_modules/sharp
gyp ERR! node -v v12.1.0



error Command failed: yarnpkg
```

After I selected yarn the installation produced this error. Would appreciate it if someone could guide me towards what I did wrong. Much thanks!

**Comment by eddiebeazer** [comment]
There is an issue with Node 12. Install node 12 and then run the yarn command.

**Comment by emanuallan** [comment]
Hey Edward. Sorry I'm not sure what you mean. The issue is with node 12 but i should install node 12? I upgraded my node to 12.4 but it still doesn't work.

**Comment by eddiebeazer** [comment]
The issue is with a plugin called sharp that doesn’t work with node 12 yet. the sharp plugin works with node 11. You can install it by using nvm(https://github.com/nvm-sh/nvm) and then running the command nvm use node 11 which will change your node version to 11. After that, delete your node_modules folder, install packages nvm npm install or yarn and then it should work.

Edward Beazer
React Developer
617-797-6926
https://www.edwardbeazer.com

**Comment by eddiebeazer** [comment]
The issue is with a plugin called sharp that doesn’t work with node 12 yet. the sharp plugin works with node 11. You can install it by using [nvm](https://github.com/nvm-sh/nvm) and then running the command `nvm use node 11` which will change your node version to 11. After that, delete your `node_modules` folder, install packages nvm ```npm install``` or `yarn` and then it should work.

**Comment by astr0sl0th** [comment]
The best solution is to install `npm i gatsby-transformer-sharp@latest` then you can use node latest or node 12 if you wish.

**Comment by rathorehq** [comment]
> The best solution is to install `npm i gatsby-transformer-sharp@latest` then you can use node latest or node 12 if you wish.

It didn't worked for me, can you guide me further? Like what exactly I have to do?

**Comment by rathorehq** [comment]
> The issue is with a plugin called sharp that doesn’t work with node 12 yet. the sharp plugin works with node 11. You can install it by using [nvm](https://github.com/nvm-sh/nvm) and then running the command `nvm use node 11` which will change your node version to 11. After that, delete your `node_modules` folder, install packages nvm `npm install` or `yarn` and then it should work.

I did everything mentioned but it does not work.

**Comment by rathorehq** [comment]
I am getting this new error now after changing my node version to 11.0.0
![newer](https://user-images.githubusercontent.com/59700645/95058397-19978480-0715-11eb-8e19-89337f69507e.PNG)
